### ISSUE TITLE
EFI - No worky

### ISSUE THREAD

**Issue by Birdabo404** [unitedastronomer/E1-572G-Hackintosh#2]
Hello, I tried using your EFI but I can't go past the boot screen when it chimes - Just black screen. I was wondering if I should change the ACPI files to suit my laptop but we kinda have the same hardware, I'm not sure as well if I need to configure your PlatformInfo > Generic info to suit my laptop too.

I'm using the good ol pal - Acer Aspire E1-572 w/out the G

a reply would be appreciated :)

**Comment by unitedastronomer** [comment]
Hi, sorry. Can you drop your ACPI table, and info dump via OCSysInfo?

**Comment by unitedastronomer** [comment]
I'll try to test it again, I'll reply in a bit.

**Comment by Birdabo404** [comment]
Hello, thank you for replying! I have managed to make it work using this[ EFI](https://github.com/Gilberto-Mascena/Laptop-Acer-E1-572) that is tailored for my Laptop but unfortunately the trackpad isn't worky and isn't recognized or found, I was wondering if you could help me out with this? Also do you still want me to drop my ACPI using SDDTTime?

**Comment by unitedastronomer** [comment]
May I know what version are you trying to run? I have adjusted their config, could you try this? 
[EFI.zip](https://github.com/unitedastronomer/E1-572G-Hackintosh/files/15103539/EFI.zip)

**Comment by Birdabo404** [comment]
Hello, I'm so sorry for the late reply I have been trying to fix this last night and it took 5 hours to install, and that was just the installing of the OS part 😩 I'm currently running MacOS BIg Sur Version 11.7.10. I will be trying your config now Thank you so much!!

**Comment by unitedastronomer** [comment]
You're welcome, I'm happy to help. Update me if it worked. xx

**Comment by Birdabo404** [comment]
Currently typing this with the config that you provided, The touchpad is now present in the setting and the gestures are working but I believe there is a bug because IT IS UNBELIEVABLE SLOW specially the vertical movement of the touchpad. or I might jus be really dummy and cant use a mac lmao. 

-I have turned up the setting to the highest sensitivity but not worky aswell :c
This is the 
[EFI_CURRENT.zip](https://github.com/unitedastronomer/E1-572G-Hackintosh/files/15106222/EFI_CURRENT.zip)
before using the one you sent.

**Comment by unitedastronomer** [comment]
That's weird, the kexts are working correctly on my end, and I can speed it up the really fast. Is the OS correctly detecting your battery? If not, then that might the issue - weird issue with macOS.
Do mouse and trackpad both showing up in your settings?

Can you try this? [EFI-5-2.zip](https://github.com/unitedastronomer/E1-572G-Hackintosh/files/15106864/EFI-5-2.zip)
^ I added [ECEnabler](https://github.com/1Revenger1/ECEnabler)

**Comment by Birdabo404** [comment]
I know it is really weird, I dunno if this is relevant at all but my touchpad works with the EFI that I SENT YOU but I couldn't use any gesture/scroll/adjust sensitivity or anything else. I believe it might be tricking the system to be as a mouse instead of a touchpad but the thing is the mouse setting doesnt do anything ;-; 

With the EFI that you sent, both the mouse and trackpad showed up in the settings tho the sensitivity doesn't work. The OS is detecting my battery fine but not the touchpad when I switch to my EFI. 

Will be trying your new EFI now, thank you so much!! I really appreciate that you're replying to me still. 😭
Please let me know if you need me to provide you with SSDT's or anything else that can help :)

**Comment by Birdabo404** [comment]
Tried your new [Uploading EFI-5-2.zip…]() and Everything was working good, The trackpad sensitivity was responding amazing up until I start doing any gesture, it goes back to the bug that I talked about when it becomes really slow and the sensitivity slider doesn't do anything. It is really weird.

**Comment by unitedastronomer** [comment]
i think it was because of the hacky way they implemented for gestures to work.

>** Due to the limitations of PS/2 bus, Synaptics touchpad reports only the number of fingers and coordinates of two of them to the computer. When there are two fingers on the touchpad and third finger is added, a 'jump' may happen, because the coordinates of one of the fingers are replaced with the coordinates of the added finger. Finger renumbering algorithm estimates the distance from old coordinates to new ones in order to hide this 'jump' from the OS and to calculate approximate position of the 'hidden' finger, in assumption that fingers move together in parallel to each other. Now third and fourth fingers are reported at the same position as one of the first two fingers. It allows Launchpad/Show desktop gesture to work more reliably.

\- from the Acidanthera's [VoodooPS2 repo](https://github.com/acidanthera/VoodooPS2)

**Comment by unitedastronomer** [comment]
I am not sure if you have already generated your SMBIOS data, you could follow this [guide](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#fixing-imessage-and-other-services-with-opencore). As for the ROM, just use your ethernet's MAC address.

**Comment by Birdabo404** [comment]
Hmmm that suckssss so much ;-; oh welp haha, What EFI do you suggest I should use btw?  I will be generating my SMBIOS as soon as you recommend me what EFI I should use; the one I sent or the latest one you sent? Also does it matter what Mac I should use for the SMBIOS? Dortania OpenCore recommends that I should use iMac14,4 for Haswell but I kinda wanna use a MB instead of iMac. 

Do you also happen to know how to fix my remaining USB ports? ;-; They're not functional anymore apart from the one I use to install the OS. 

I would also like to say Thank youu so much for taking the time to reply to my issues!! 🙌

**Comment by Birdabo404** [comment]
One last thing, The wifi logo on the menu is stuck on 1 bar I was wondering if you've got fix for that since we have the same wifi card; Atheros AR9565

I also noticed that you changed the option key to the windows key when I used your EFI, how you do that ;-;

**Comment by unitedastronomer** [comment]
> I also noticed that you changed the option key to the windows key when I used your EFI, how you do that ;-;

Go to `VoodooPS2Controller.kext` > right click > show package contents > PlugIns > `VoodooPS2Keyboard.kext` > Open `Info.plist` with plist editor (Propertree is what I use)> `IOKitPersonalities` > `ApplePS2Keyboard` > `Default` > `Swap command and option` > change `No` to `Yes`.

> One last thing, The wifi logo on the menu is stuck on 1 bar I was wondering if you've got fix for that since we have the same wifi card; Atheros AR9565


It was always like that, I got annoyed by it so I hid it using HiddenBar.app. I warn you, that card is slow af.

**Comment by unitedastronomer** [comment]
> does it matter what Mac I should use for the SMBIOS? Dortania OpenCore recommends that I should use iMac14,4 for Haswell but I kinda wanna use a MB instead of iMac.

There is a separate guide for Desktop and Laptop, it's easy to miss (I did).

> What EFI do you suggest I should use btw? I will be generating my SMBIOS as soon as you recommend me what EFI I should use; the one I sent or the latest one you sent?


The one I sent, I cleaned up that config a little.

**Comment by Birdabo404** [comment]
Thank you so much!! You've been amazingg 🤍

**Comment by unitedastronomer** [comment]
you're welcome!!!!!!!! xx our laptops are actually almost identical, the `ADDITIONAL_INFO.md` in this repo should still be relevant for you. xx <3

**Comment by unitedastronomer** [comment]
> Do you also happen to know how to fix my remaining USB ports? ;-; They're not functional anymore apart from the one I use to install the OS.

Hey I'm sorry I missed this, you could do it by remapping the USB with [USBMap](https://github.com/corpnewt/USBMap).

You can try mine, don't mind the duplicate naming you see if you are using Hackintool. It's a weird issue when you once logged in with Windows, and then to macOS, the USB ports from XHC transfers to EHC/EH01 controller after sleep.

[USBMap.kext.zip](https://github.com/unitedastronomer/E1-572G-Hackintosh/files/15108757/USBMap.kext.zip)

**Comment by Birdabo404** [comment]
I tried making my own USBMap.Kext because my SMBIOS Does not match yours and I have unfortunately managed to break my EFI boot ;-; now it's currently looping on the apple logo, Can I still save this or do I need to reinstall the whole OS? I tried parching in my usb so I can boot it from there but its a no go idk why

**Comment by Birdabo404** [comment]
I have managed to use your USBMap.kext file by redoing my SMBIOS to what is compatible :D Everything works well now apart from the REALLY slow touchpad :c it works well up until I use the scroll gesture then it feels like all the settings for it gets defaulted to the very slow sensitivity. Hoping for a fix to this, I really wanna daily drive this laptop for UNI 😩

**Comment by unitedastronomer** [comment]
Hey sorry, it took me a while to reply. :<

> I have 5 EFI folders on my usb drive that's why

Just keep one folder, I personally use [Bootloader Chooser](https://github.com/jief666/BootloaderChooser), and have my main OC folder and the test versions. 
  * In order to switch OC folders, I smash F12 key, then the `\` key, and that should show up the different OC folders. 

> now it's currently looping on the apple logo, Can I still save this or do I need to reinstall the whole OS? I tried parching in my usb so I can boot it from there but its a no go idk why 

If this ever happens again, then it's an EFI issue, not OS issue, do not re-install unless you imported kexts to System/Library/Extensions.

# 

Do you have Hackintool? Can you check if the Broadcom ethernet is `En0` and set as `built-in`? If not, you can add `built-in | 01 | Data` to `PciRoot(0x0)/Pci(0x1C,0x0)/Pci(0x0,0x0)` , this is important in order for iServices to work. ([ref](https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#what-if-i-don-t-have-en0-at-all))

# 

You may notice that laptop won't sleep at critical level, I personally use HibernationFixup to "fix" it.
Add Hibernation fixup, then add `E09B9297-7928-4440-9AAB-D1F8536FBF0A` under `Add` in NVRAM section, then under that, add `hbfx-ahbm | 3969 | Number`, under `Delete`, add `hbfx-ahbm` ([ref](https://github.com/acidanthera/HibernationFixup))

#

For editing config.plist files, I use Opencore Configurator, just don't shutdown immediately after you save the plist as it may get corrupted.

**Comment by unitedastronomer** [comment]
I managed to speed up the scrolling speed, however it requires using the old VoodooPS2Controller by Rehabman instead of the updated Acidanthera version. I'll update you once I get it to work right on my end.

**Comment by unitedastronomer** [comment]
[EFI-5-2-3.zip](https://github.com/unitedastronomer/E1-572G-Hackintosh/files/15123618/EFI-5-2-3.zip)

I had adjusted it with the trackpad scroll speed fix, auto sleep/hibernate on critical battery level, set ethernet as built-in, just copy your previous SMBIOS data back to this one.

**Comment by unitedastronomer** [comment]
That's a temporary fix, the 3 finger swipe don't work because I used the old VoodooPS2Controller kext by Rehabman that did not utilize VoodooPS2Input, I am still trying to figure out how to make it work with the latest/Acidanthera version.

**Comment by Birdabo404** [comment]
Sorry for the late reply, My brave was acting up and I cannot find the reason why. 

I am currently using the newly provided EFI and it works fantastic! Though I don't mind the gesture since I use the CTRL-Arrow keys to move through workspaces, I wish there is at least a scroll gesture hahah even like an edge scroll something similar to linux and windows idk if that's available in macOS. 

> Regarding with the Broadcom ethernet and hackintool stuff, Do I need to do these still or nope? If yes then please do give me a reply back. Thank you so much for updating the EFI files btw!! rlly appreciate it.

**Comment by Birdabo404** [comment]
> Import your current working EFI/OC folder to the EFI partition of your SSD/HDD, then import this to your USB and boot from it to test it.

- I just directly replaced my EFI from the one you sent ;-; Im pretty sure this is bad practice and not good if I destroy my EFI again ahah XD.

**Comment by unitedastronomer** [comment]
> My brave was acting up and I cannot find the reason why.

i think things broke because of SMBIOS changes, I don't know how to fix this issue :< 

> Regarding with the stuff on top, Do I need to do these still or nope? If yes then please do give me a reply back. 

Only if you need iServices, don't worry I already adjusted the config.plist for that. Just run the terminal commands and then restart to reset the en0.

> Thank you so much for updating the EFI files btw!! rlly appreciate it.

you're welcomee!! ^_^


the trackpad speed can be adjusted in the SSDT-KBC0, i never really tested to adjust it, it just worked on my first try, i just copied some values present [here](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/blob/master/SSDT-Thinkpad_Clickpad.dsl).

**Comment by Birdabo404** [comment]
> i think things broke because of SMBIOS changes, I don't know how to fix this issue :<
- I'm not sure if its because of that, The popup error only appears when I open the brave settings, I might got a hint that It might be because of DRM stuff or sumthn? I dunno lemme further investigate it.

> the trackpad speed can be adjusted in the SSDT-KBC0, i never really tested to adjust it, it just worked on my first try, i just copied some values present [here](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/blob/master/SSDT-Thinkpad_Clickpad.dsl).
- I haven't opened an SSDT file before ;-; are those the .aml stuff? Do I just write over it using a text editor? I was going to ask you how to change the sensitivity since it's a little bit slow for my liking hahah but thank you!

**Comment by Birdabo404** [comment]
I've been also meaning to ask you, My audio output is my headphones port instead of the speakers. Now I wonder if this is a hardware issue or a driver because I could hear the chime perfectly on boot. 

This has also been an issue with me when I was using linux. So I'm 90% guessing that it might be hardware issue but it working on boot with chime makes my out the remaining 10% a doubt that it is, so I'm not quite sure what to do.

The sound on headphones works good btw, It's just nada on speakers, the speakers aren't even on the option to output sounds XD.
![Screen Shot 2024-04-26 at 3 59 37 PM](https://github.com/unitedastronomer/E1-572G-Hackintosh/assets/140108872/d3e2d33d-3367-4899-b58c-814413603ab9)

**Comment by unitedastronomer** [comment]
lol i am a dumbass, you can actually adjust the scroll speed in the settings. it is under **Accessibility** >  **Pointer Control** in Sonoma.

This is what one of the authors/maintainers of the VoodooPS2 said to me.
![Screenshot 2024-04-26 at 3 51 54 PM](https://github.com/unitedastronomer/E1-572G-Hackintosh/assets/155970773/6a74cae2-3da8-4107-a25a-3401561fb35c)
 


[EFI-5-2-3-3 2.zip](https://github.com/unitedastronomer/E1-572G-Hackintosh/files/15127217/EFI-5-2-3-3.2.zip), i re-added the new voodoops2, while at it, i also added a patch so the ethernet's model in sysreport shows correctly. all you have to do is re-import your SMBIOS haha hehe.

**Comment by unitedastronomer** [comment]
try replacing the applealc.kext from [here](https://github.com/acidanthera/AppleALC) , i replaced the applealc with mine - i compiled it specifically for alc282 layout 28 (same as yours), so that might be an issue.

then, if that did not fix the issue, then it might be an irq issue. you will need to drop your ACPI table (just use [maciasl](https://github.com/acidanthera/MaciASL)), and save the DSDT. download SSDTTime and fix IRQ, choose the `only conflicting IRQ` option. it will generate both .asl and patches.plist, use the merge.command and drag and drop the config.plist into it. and then replace the SSDT-HPET.aml. i'm sorry if this is kinda confusing, i see that you know how to code so i'm assuming this will be easy for you (i'm a noob).

**Comment by Birdabo404** [comment]
> lol i am a dumbass, you can actually adjust the scroll speed in the settings. it is under **Accessibility** > **Pointer Control** in Sonoma.

- Regarding this I meant that I have no gesture to scroll at all ;-; like two finger scrolling? Don't exist. Edge Scrolling? nope, Don't exist. 

- Thank you I will be giving the new EFI a try :D

**Comment by unitedastronomer** [comment]
i also forgot to tell, once you plug a headphone, it will set as "headphone", if unplugged then it should turn into "internal speakers", this is an issue with real macs too.

**Comment by Birdabo404** [comment]
Nope, No trackpad found :D 

Also I did the DSDT file thingy using maciASL, do you still want me to do the SSDTTime stuff along with it? 

[System DSDT.zip](https://github.com/unitedastronomer/E1-572G-Hackintosh/files/15127672/System.DSDT.zip)

**Comment by unitedastronomer** [comment]
hold on, i'll get with u in a minute. that "no trackpad found" happens when there's no batter. the rehabman version of voodoops2 emulates the trackpad as a mouse, that might be an issue if you're using that version i previously made, that could also be it. 

>  do you still want me to do the SSDTTime stuff along with it?

no need i'll do it xx

**Comment by Birdabo404** [comment]
> i also forgot to tell, once you plug a headphone, it will set as "headphone", if unplugged then it should turn into "internal speakers", this is an issue with real macs too.

- yeah nothing happens when I unplug my headphones :c As I've mentioned its still the same thing as I was using linux, so I hope it won't be a waste of your efforttt ahhhh

**Comment by Birdabo404** [comment]
> hold on, i'll get with u in a minute. that "no trackpad found" happens when there's no batter. the rehabman version of voodoops2 emulates the trackpad as a mouse, that might be an issue if you're using that version i previously made, that could also be it.

-hmmm that's weird, I am currently running on my batter ;-; lmaoo

**Comment by Birdabo404** [comment]
I'm on your new EFI and the trackpad is now found and present on the setting, Everything works good but as soon as I use a gesture or like specifically the two finger scroll gesture to scroll it becomes slow specially the vertical movement :< I might have to just use EFI I used before and be satisfied with the trackpad `just working` without any scroll gesture huhu 

ELANTECH touchpad sucks b@lls XD

**Comment by unitedastronomer** [comment]
[EFI-HPET+XOSI.zip](https://github.com/unitedastronomer/E1-572G-Hackintosh/files/15127876/EFI-HPET%2BXOSI.zip)

can you try this? i have added ssdt-xosi, adjusted the ssdt-hpet, and replaced the applealc from the release one, this also has latest voodoops2. can u try this one with a USB? hehe, and make sure it is living alone in the efi haha

**Comment by unitedastronomer** [comment]
>  as I use a gesture or like specifically the two finger scroll gesture to scroll it becomes unbearably slow  


try adjusting in settings first, i just tested it. it's under accessibility.

**Comment by unitedastronomer** [comment]
> ELANTECH touchpad sucks b@lls XD

REALLLLL

**Comment by Birdabo404** [comment]
>try adjusting in settings first, i just tested it. it's under accessibility. 
- I think you might have misunderstood me ;-; I don't mean that the scroll starts slowing down but-- Here's an example of what I mean when I said everything works alright up until I do a two finger gesture then the mouse sensitivity changes ;-; really slow 

https://github.com/unitedastronomer/E1-572G-Hackintosh/assets/140108872/9324ff4b-4625-4f5b-9ae9-0244e6162f6d

**Comment by unitedastronomer** [comment]
> I think you might have misunderstood me ;-; I don't mean that the scroll starts slowing down but-- Here's an example of what I mean when I said everything works alright up until I do a two finger gesture then the mouse sensitivity changes

oooh oops sorry xD, that's weird, i just tried it and i can't replicate it, our laptop are literally identical except for the CPU, so it might be an OS issue.


https://github.com/unitedastronomer/E1-572G-Hackintosh/assets/155970773/4b9d8a77-186a-4c89-b732-70b35e88990d

**Comment by unitedastronomer** [comment]
wait i'm curious, do you also get the "8 apples glitch" at boot?

**Comment by Birdabo404** [comment]
dudee Monterey looks so cleannnn, I would change but I wouldn't get any wifi T-T might buy a new wifi card in Hope that its an OS problem. 

Also what's an 8 Apple glitch ;-; I do get a glitch on boot tho like it spazzes, kinda like Loki being in the wrong timeline type.

**Comment by unitedastronomer** [comment]
> I do get a glitch on boot tho like it spazzes, kinda like Loki being in the wrong timeline type. yes that thing
![Screenshot 2024-04-26 at 5 39 55 PM](https://github.com/unitedastronomer/E1-572G-Hackintosh/assets/155970773/f4857992-0a31-4b40-b190-de79384cb5c0)



> might buy a new wifi card in Hope that its an OS problem.

i was forced to replaced it, bc it was too slow for me. try setting your router to 40mhz, that should atleast make the speed a little bit more tolerable.

**Comment by Birdabo404** [comment]
May I ask what BIOS version do you have atm? I'm trying to see if my touchpad issue is related to my BIOS version. I currently have the v2.17

**Comment by Birdabo404** [comment]
I have FOUND a working kext for my touchpad, The scrolling is a little bit good though the 3 finger gesture is still REALLY wonky :< so I can't use other gestures. Imma just drop it here incase you know how to fix it ahah 

[VoodooPS2Controller-2.zip](https://github.com/unitedastronomer/E1-572G-Hackintosh/files/15131973/VoodooPS2Controller-2.zip)

link: https://github.com/BAndysc/VoodooPS2/releases/tag/0.4
